### ISSUE TITLE
`renderjson` variable leaks to global scope

### ISSUE THREAD

**Issue by milotoor** [caldwell/renderjson#11]
Due to the way the [module is exported](https://github.com/caldwell/renderjson/blob/6466286/renderjson.js#L54), the `renderjson` identifier (and the IIFE it is initialized to) is leaked into the global scope. Declaring it as a variable first and then initializing it with the IIFE would prevent the leak, be trivial to do, and not break any existing code. I'm happy to put together a PR.

**Comment by geekytime** [comment]
Along the same lines, I'd like to use this via npm with webpack, but right now the export is `{}`.

**Comment by caldwell** [comment]
@geekytime, Not sure why webpack isn't working for you. I just tried a test and it appeared to correctly export the function. Open a new bug if it's still broken, please.
