### ISSUE TITLE
TypeError: Cannot read property 'append' of null

### ISSUE THREAD

**Issue by zohaibhassan122** [caldwell/renderjson#16]
Hi Dear,
I am trying to use your library and I am facing this problem.
Below is the code. Can you help me on this   

angular.element(document).ready(function () {
        renderjson.set_icons('+', '-');
        renderjson.set_show_to_level(1);

        var jsonstuff =  document.querySelector("#json");
        console.log(jsonstuff);
        jsonstuff.append(
            renderjson( $scope.nsdJSON)
        );

    });

**Comment by caldwell** [comment]
That sounds like your `jsonstuff` variable is null, and not anything to do with `renderjson()`. I suspect your `document.querySelector("#json")` line isn't finding the tag with id `json`.

**Comment by zohaibhassan122** [comment]
Thanks a lot for your help.
My problem is solved.
