### ISSUE TITLE
show_to_level overrides set_max_string_length

### ISSUE THREAD

**Issue by Almenon** [caldwell/renderjson#20]
I would expect set_max_string_length to work regardless of the level set.  For example, if a large paragraph comes along in the first level you would want to show the first part of the paragraph, but truncate the rest.

The description for max_string_length implies it works regardless of level:
> Strings will be truncated and made expandable if they are longer than
length. As a special case, if length is the string "none" then there
will be no truncation. The default is "none".

Instead what happens is that if the string is in a shown level, the string is expanded by default.

**Comment by caldwell** [comment]
Yeah, I'd expect that too. The string and array/object disclosures all share the same code and so they all behaved the same. It should be an easy fix.

**Comment by Almenon** [comment]
You are awesome! thanks :)
