### ISSUE TITLE
Issue on IE11

### ISSUE THREAD

**Issue by champix** [caldwell/renderjson#21]
Hi !

renderjson doesn't seem to work on IE11.
Can you confirm ?

I get an error about the "assign" method not being supported.

I am running IE11 on win 10 with no "emulation" mode.

Thanks in advance

**Comment by caldwell** [comment]
Looks like IE11 doesn't have `Object.assign()`. To get renderjson to work on an older browser like that, you'll need a [polyfill for `Object.assign()`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object/assign#Polyfill). Just drop it in before renderjson runs and that should fix this issue (there may be others—I've never tested on IE11).

**Comment by champix** [comment]
Thanks man ! You rock.
