### ISSUE TITLE
License name?

### ISSUE THREAD

**Issue by akmehta** [caldwell/renderjson#7]
Hi, I was wondering if your license was part of a named license. I was looking at using this library for a company project, and there's only some licenses I am allowed to use.

**Comment by caldwell** [comment]
[ISC License](https://en.wikipedia.org/wiki/ISC_license). I had to look it up myself by pasting the text into google. :-) Perhaps I should amend it to mention the name.

**Comment by caldwell** [comment]
I've amended the Readme so it's mentioned by name.
